FROM node:22-alpine3.20 AS builder

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . .

RUN npm run build

FROM node:22-alpine3.20

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/dist ./dist

CMD [ "npm", "run", "start:prod" ]
