services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev 
    ports:
      - '3000:3000'
    environment:
      - DB_URL=postgres://postgres:postgres@pg:5432/mydb
    restart: unless-stopped
    depends_on:
      - pg

  pg:
    image: postgres:17.5-alpine3.21
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    restart: unless-stopped

volumes:
  postgres-data:
